packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@halo-trace/sdk@1.0.0'
