DO $$ BEGIN
    CREATE TYPE "AiProvider" AS ENUM ('HALO_MANAGED', 'GEMINI', 'OPENAI');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "AiConnectionStatus" AS ENUM ('NOT_CONFIGURED', 'CONNECTED', 'FAILED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "aiProvider" "AiProvider" NOT NULL DEFAULT 'HALO_MANAGED';
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "aiEncryptedKey" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "aiKeyPrefix" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "aiKeySuffix" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "aiModel" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "aiStatus" "AiConnectionStatus" NOT NULL DEFAULT 'NOT_CONFIGURED';
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "aiLastTestedAt" TIMESTAMP(3);
